(()=>{'use strict';
const game=document.getElementById('game'); if(!game)return;
const old=game.querySelector('#world'); if(old)old.style.display='none';
const style=document.createElement('style');style.textContent=`#battleCanvas{position:absolute;inset:0;width:100%;height:100%;z-index:2;background:#74ccef}.battleHud{position:absolute;inset:0;z-index:10;pointer-events:none;font-family:Arial,sans-serif}.bhBox{position:absolute;background:#101a2ddd;border:1px solid #ffffff26;box-shadow:0 4px 12px #0005;padding:9px 12px;font-weight:800}.bhStats{left:14px;top:14px;width:240px}.bhAmmo{right:14px;top:14px;text-align:right}.bhPrompt{left:50%;bottom:18px;transform:translateX(-50%)}.bhCross{position:absolute;left:50%;top:50%;width:18px;height:18px;transform:translate(-50%,-50%)}.bhCross:before,.bhCross:after{content:'';position:absolute;background:#fff}.bhCross:before{left:8px;width:2px;height:18px}.bhCross:after{top:8px;width:18px;height:2px}.bhBar{height:8px;background:#18263c;margin-top:6px}.bhBar i{display:block;height:100%;background:#52df82}.bhShield i{background:#57c6ff}.bhSmall{font-size:10px;color:#b9c7d7}.bhLoot{color:#ffd84d;margin-top:5px}`;document.head.appendChild(style);
const canvas=document.createElement('canvas');canvas.id='battleCanvas';game.insertBefore(canvas,game.firstChild);
const hud=document.createElement('div');hud.className='battleHud';hud.innerHTML=`<div class="bhBox bhStats"><div>SOLO · 100 PLAYERS</div><div class="bhSmall">STORMRUNNER</div><div class="bhBar"><i id="bhHp" style="width:100%"></i></div><div class="bhBar bhShield"><i id="bhShield" style="width:50%"></i></div><div class="bhLoot" id="bhLoot">AR · 30 / 120</div></div><div class="bhBox bhAmmo"><div id="bhWeapon">ASSAULT RIFLE</div><strong id="bhAmmo">30</strong> / 120</div><div class="bhCross"></div><div class="bhBox bhPrompt" id="bhPrompt">WASD move · SHIFT sprint · SPACE jump · E search chest</div>`;game.appendChild(hud);
let gl,prog,buf,count=0,verts=[],norms=[],colors=[];let loaded=false,loading=false;let objCenter=[0,0,0],scale=1,grid=null,gridN=128;const worldMin=-350,worldMax=350;const player={x:0,y:0,z:170,vy:0,onGround:true,yaw:0,hp:100,shield:50,ammo:30};const keys={};let camYaw=0,camPitch=.12,camDist=7;let houses=[],chests=[],pickups=[],bots=[];let nearby=null;
const hudPrompt=()=>document.getElementById('bhPrompt');
addEventListener('keydown',e=>{keys[e.code]=1;if(e.code==='KeyE')openChest();if(e.code==='KeyQ')buildWall()});addEventListener('keyup',e=>keys[e.code]=0);
canvas.addEventListener('click',()=>canvas.requestPointerLock?.());addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas){camYaw-=e.movementX*.0025;camPitch=Math.max(-.35,Math.min(.45,camPitch-e.movementY*.0016));}});addEventListener('mousedown',e=>{if(document.pointerLockElement===canvas&&e.button===0)shoot()});addEventListener('wheel',e=>{camDist=Math.max(4.5,Math.min(10,camDist+e.deltaY*.01))});
function resize(){const d=Math.min(2,devicePixelRatio||1);canvas.width=innerWidth*d;canvas.height=innerHeight*d;if(gl)gl.viewport(0,0,canvas.width,canvas.height)}addEventListener('resize',resize);resize();
function shader(t,s){const q=gl.createShader(t);gl.shaderSource(q,s);gl.compileShader(q);if(!gl.getShaderParameter(q,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(q));return q}
function initGL(){gl=canvas.getContext('webgl',{antialias:true,alpha:false});if(!gl)throw Error('WebGL unavailable');const vs=`attribute vec3 aP;attribute vec3 aN;attribute vec3 aC;uniform mat4 uM;varying vec3 vC;varying float vL;void main(){gl_Position=uM*vec4(aP,1.);vC=aC;vL=.42+.58*max(dot(normalize(aN),normalize(vec3(-.5,.9,.3))),0.);}`;const fs=`precision mediump float;varying vec3 vC;varying float vL;void main(){gl_FragColor=vec4(vC*vL,1.);}`;prog=gl.createProgram();gl.attachShader(prog,shader(gl.VERTEX_SHADER,vs));gl.attachShader(prog,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(prog);if(!gl.getProgramParameter(prog,gl.LINK_STATUS))throw Error('shader link failed');prog.p=gl.getAttribLocation(prog,'aP');prog.n=gl.getAttribLocation(prog,'aN');prog.c=gl.getAttribLocation(prog,'aC');prog.m=gl.getUniformLocation(prog,'uM');gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.cullFace(gl.BACK)}
function perspective(f,a,n,far){const q=1/Math.tan(f/2),nf=1/(n-far);return new Float32Array([q/a,0,0,0,0,q,0,0,0,0,(far+n)*nf,-1,0,0,2*far*n*nf,0])}
function lookAt(e,t){let zx=e[0]-t[0],zy=e[1]-t[1],zz=e[2]-t[2],l=Math.hypot(zx,zy,zz)||1;zx/=l;zy/=l;zz/=l;let xx=zz,xz=-zx,xl=Math.hypot(xx,xz)||1;xx/=xl;xz/=xl;const yx=zy*xz,yy=zz*xx-zx*xz,yz= -zy*xx;return new Float32Array([xx,yx,zx,0,0,yy,zy,0,xz,yz,zz,0,-(xx*e[0]+xz*e[2]),-(yx*e[0]+yy*e[1]+yz*e[2]),-(zx*e[0]+zz*e[2]),1])}
function matMul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o}
function groundAt(x,z){if(!grid)return 0;const gx=Math.max(0,Math.min(gridN-1,Math.round((x-worldMin)/(worldMax-worldMin)*(gridN-1))));const gz=Math.max(0,Math.min(gridN-1,Math.round((z-worldMin)/(worldMax-worldMin)*(gridN-1))));return grid[gz*gridN+gx]||0}
function addTri(a,b,c,col){const ux=b[0]-a[0],uy=b[1]-a[1],uz=b[2]-a[2],vx=c[0]-a[0],vy=c[1]-a[1],vz=c[2]-a[2],nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx,l=Math.hypot(nx,ny,nz)||1;for(const p of [a,b,c]){verts.push(...p);norms.push(nx/l,ny/l,nz/l);colors.push(...col)}}
function addBox(x0,y0,z0,x1,y1,z1,col){const v=[[x0,y0,z0],[x1,y0,z0],[x1,y1,z0],[x0,y1,z0],[x0,y0,z1],[x1,y0,z1],[x1,y1,z1],[x0,y1,z1]];addTri(v[0],v[1],v[2],col);addTri(v[0],v[2],v[3],col);addTri(v[4],v[6],v[5],col);addTri(v[4],v[7],v[6],col);addTri(v[0],v[4],v[5],col);addTri(v[0],v[5],v[1],col);addTri(v[3],v[2],v[6],col);addTri(v[3],v[6],v[7],col);addTri(v[1],v[5],v[6],col);addTri(v[1],v[6],v[2],col);addTri(v[0],v[3],v[7],col);addTri(v[0],v[7],v[4],col)}
function addHouse(x,z,s){const y=groundAt(x,z);houses.push({x,z,y,s});addBox(x-9*s,y,x-7*s,x+9*s,y+9*s,z+7*s,[.69,.48,.32]);addBox(x-10*s,y+9*s,z-8*s,x+10*s,y+16*s,z+8*s,[.43,.10,.10]);addBox(x-3*s,y+1,z-7.5*s,x+3*s,y+6,z-7.1*s,[.13,.25,.32]);addBox(x-8*s,y+3,z+7.2*s,x-3*s,y+7,z+7.5*s,[.17,.48,.68])}
function addChest(x,z){const y=groundAt(x,z)+1.2;const ch={x,z,y,open:false};chests.push(ch);addBox(x-2,y-1,z-1,x+2,y+1,z+1,[.56,.32,.05]);addBox(x-2,y+1,z-1,x+2,y+1.8,z+1,[.91,.66,.09])}
function addPickup(x,z,type){const y=groundAt(x,z)+1.2;const p={x,z,y,type,taken:false};pickups.push(p);addBox(x-.8,y-.5,z-.8,x+.8,y+.5,z+.8,type==='ammo'?[.9,.8,.1]:type==='shield'?[.1,.55,.95]:[.75,.15,.72])}
function addBot(x,z){const y=groundAt(x,z);bots.push({x,z,y,hp:100});addBox(x-1,y,x-1,x+1,y+4,z+1,[.86,.20,.22]);addBox(x-1.3,y+4,z-1.3,x+1.3,y+6,z+1.3,[.95,.72,.45])}
async function load(){if(loading||loaded)return;loading=true;try{initGL();const r=await fetch('fnscan.obj',{cache:'no-store'});if(!r.ok)throw Error('fnscan.obj not found');const text=await r.text();const lines=text.split(/\r?\n/),V=[],mn=[Infinity,Infinity,Infinity],mx=[-Infinity,-Infinity,-Infinity];for(const line of lines)if(line.startsWith('v ')){const a=line.trim().split(/\s+/);const x=+a[1],y=+a[2],z=+a[3];V.push(x,y,z);mn[0]=Math.min(mn[0],x);mn[1]=Math.min(mn[1],y);mn[2]=Math.min(mn[2],z);mx[0]=Math.max(mx[0],x);mx[1]=Math.max(mx[1],y);mx[2]=Math.max(mx[2],z)}objCenter=[(mn[0]+mx[0])/2,(mn[1]+mx[1])/2,(mn[2]+mx[2])/2];scale=680/Math.max(mx[0]-mn[0],mx[1]-mn[1],mx[2]-mn[2]);grid=new Float32Array(gridN*gridN);const countGrid=new Uint16Array(gridN*gridN);for(let i=0;i<V.length;i+=3){const x=(V[i]-objCenter[0])*scale,y=(V[i+1]-objCenter[1])*scale,z=(V[i+2]-objCenter[2])*scale;const gx=Math.max(0,Math.min(gridN-1,Math.round((x-worldMin)/(worldMax-worldMin)*(gridN-1)))),gz=Math.max(0,Math.min(gridN-1,Math.round((z-worldMin)/(worldMax-worldMin)*(gridN-1)))),gi=gz*gridN+gx;if(!countGrid[gi]||y>grid[gi])grid[gi]=y;countGrid[gi]=1}for(let gz=0;gz<gridN;gz++)for(let gx=0;gx<gridN;gx++){const gi=gz*gridN+gx;if(countGrid[gi])continue;let sum=0,n=0;for(let dz=-2;dz<=2;dz++)for(let dx=-2;dx<=2;dx++){const xx=gx+dx,zz=gz+dz;if(xx>=0&&xx<gridN&&zz>=0&&zz<gridN){const si=zz*gridN+xx;if(countGrid[si]){sum+=grid[si];n++}}}grid[gi]=n?sum/n:0}
for(let i=0;i<lines.length;i++){const line=lines[i];if(!line.startsWith('f '))continue;const ids=line.trim().split(/\s+/).slice(1).map(s=>{const n=parseInt(s.split('/')[0],10);return n<0?V.length/3+n:n-1});for(let k=1;k<ids.length-1;k++){const t=[ids[0],ids[k],ids[k+1]],a=t.map(id=>[(V[id*3]-objCenter[0])*scale,(V[id*3+1]-objCenter[1])*scale,(V[id*3+2]-objCenter[2])*scale]);const ux=a[1][0]-a[0][0],uy=a[1][1]-a[0][1],uz=a[1][2]-a[0][2],vx=a[2][0]-a[0][0],vy=a[2][1]-a[0][1],vz=a[2][2]-a[0][2];const nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx,l=Math.hypot(nx,ny,nz)||1;for(const p of a){addTri(p,p,p,[.23,.48,.20]);norms.splice(norms.length-9,9,nx/l,ny/l,nz/l,nx/l,ny/l,nz/l,nx/l,ny/l,nz/l)}}if(i%3000===0){const pct=Math.min(95,Math.round(i/lines.length*100));const bar=document.querySelector('#bhProgress');if(bar)bar.textContent='Loading island '+pct+'%';await new Promise(requestAnimationFrame)}}
// Clear malformed self-tris and rebuild terrain from raw face data in a second pass.
verts=[];norms=[];colors=[];for(let i=0;i<lines.length;i++){const line=lines[i];if(!line.startsWith('f '))continue;const ids=line.trim().split(/\s+/).slice(1).map(s=>{const n=parseInt(s.split('/')[0],10);return n<0?V.length/3+n:n-1});for(let k=1;k<ids.length-1;k++){const a=ids[0],b=ids[k],cc=ids[k+1],A=[(V[a*3]-objCenter[0])*scale,(V[a*3+1]-objCenter[1])*scale,(V[a*3+2]-objCenter[2])*scale],B=[(V[b*3]-objCenter[0])*scale,(V[b*3+1]-objCenter[1])*scale,(V[b*3+2]-objCenter[2])*scale],C=[(V[cc*3]-objCenter[0])*scale,(V[cc*3+1]-objCenter[1])*scale,(V[cc*3+2]-objCenter[2])*scale];const ux=B[0]-A[0],uy=B[1]-A[1],uz=B[2]-A[2],vx=C[0]-A[0],vy=C[1]-A[1],vz=C[2]-A[2],nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx,l=Math.hypot(nx,ny,nz)||1;const h=(A[1]+B[1]+C[1])/3;let col=h>120?[.55,.58,.38]:h<0?[.16,.38,.18]:[.23,.50,.22];addTri(A,B,C,col)}}
// Land zone: clustered houses and chests.
[[0,170,1.2],[38,185,1],[-40,170,1],[70,230,1.1],[-75,225,1],[125,185,1.15],[0,300,1.05],[170,280,1]].forEach(v=>addHouse(v[0],v[1],v[2]));[[0,160],[48,194],[-48,187],[70,250],[-70,242],[118,176],[10,300],[180,270]].forEach(v=>addChest(v[0],v[1]));[[22,208,'ammo'],[-20,214,'rifle'],[58,214,'shield'],[-58,205,'ammo']].forEach(v=>addPickup(v[0],v[1],v[2]));[[115,210],[-110,215],[150,140],[-150,140],[200,245],[-200,250]].forEach(v=>addBot(v[0],v[1]));
// Ground the player inside the POI.
player.x=0;player.z=170;player.y=groundAt(player.x,player.z)+4;player.yaw=0;camYaw=0;camPitch=.12;loaded=true;document.getElementById('bhPrompt').textContent='WASD move · SHIFT sprint · SPACE jump · E search chest · LMB shoot';
verts.forEach(()=>{});buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(verts),gl.STATIC_DRAW);count=verts.length/3;
}catch(e){const p=document.createElement('div');p.className='bhBox';p.style='left:50%;top:50%;transform:translate(-50%,-50%);z-index:40';p.textContent='3D MAP ERROR: '+e.message;game.appendChild(p);console.error(e)}}
function active(){return !game.classList.contains('hidden')&&getComputedStyle(game).display!=='none'}
function move(dt){if(!active()||!loaded)return;let sp=(keys.ShiftLeft||keys.ShiftRight)?34:19;let f=0,r=0;if(keys.KeyW)f++;if(keys.KeyS)f--;if(keys.KeyA)r--;if(keys.KeyD)r++;const L=Math.hypot(f,r)||1,sy=Math.sin(camYaw),cy=Math.cos(camYaw);player.x+=(r*cy+f*sy)/L*sp*dt;player.z+=(f*cy-r*sy)/L*sp*dt;player.x=Math.max(worldMin+8,Math.min(worldMax-8,player.x));player.z=Math.max(worldMin+8,Math.min(worldMax-8,player.z));const g=groundAt(player.x,player.z)+4;if(keys.Space&&player.onGround){player.vy=12;player.onGround=false}player.vy-=30*dt;player.y+=player.vy*dt;if(player.y<=g){player.y=g;player.vy=0;player.onGround=true}player.yaw=camYaw}
function openChest(){if(!loaded)return;let best=null,bd=8;for(const c of chests)if(!c.open){const d=Math.hypot(c.x-player.x,c.z-player.z);if(d<bd){bd=d;best=c}}if(!best)return;best.open=true;const types=['rifle','ammo','shield'];const type=types[Math.floor(Math.random()*types.length)];addPickup(best.x+4,best.z,type);hudPrompt().textContent='CHEST OPENED · '+type.toUpperCase()+' LOOT DROPPED';setTimeout(()=>updatePrompt(),1300)}
function updatePrompt(){let best=null,bd=8;for(const c of chests)if(!c.open){const d=Math.hypot(c.x-player.x,c.z-player.z);if(d<bd){bd=d;best=c}}hudPrompt().textContent=best?'E — SEARCH CHEST':'WASD move · SHIFT sprint · SPACE jump · E search chest · LMB shoot'}
function pickupCheck(){for(const p of pickups)if(!p.taken&&Math.hypot(p.x-player.x,p.z-player.z)<4){p.taken=true;if(p.type==='ammo')player.ammo=Math.min(120,player.ammo+30);else if(p.type==='shield')player.shield=100;else player.ammo=Math.min(120,player.ammo+15);document.getElementById('bhAmmo').textContent=player.ammo;document.getElementById('bhLoot').textContent='AR · 30 / '+player.ammo;document.getElementById('bhShield').style.width=player.shield+'%'}}
function shoot(){if(!loaded||player.ammo<=0)return;player.ammo--;document.getElementById('bhAmmo').textContent=player.ammo;const target=bots.find(b=>Math.hypot(b.x-player.x,b.z-player.z)<28);if(target)target.hp-=40;}
function buildWall(){if(!loaded)return;const d=7,s=Math.sin(camYaw),c=Math.cos(camYaw),x=player.x+s*d,z=player.z+c*d,y=groundAt(x,z)+2;addBox(x-3,y,z-.3,x+3,y+4,z+.3,[.62,.45,.22]);buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(verts),gl.STATIC_DRAW);count=verts.length/3;hudPrompt().textContent='BUILD WALL PLACED';setTimeout(updatePrompt,700)}
function draw(){if(!active()||!loaded)return;gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(.34,.69,.84,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const sy=Math.sin(camYaw),cy=Math.cos(camYaw),cp=Math.cos(camPitch),sp=Math.sin(camPitch);const front=[sy*cp,sp,cy*cp],eye=[player.x-front[0]*camDist,player.y-front[1]*camDist+2,player.z-front[2]*camDist],target=[player.x,player.y+2,player.z],view=lookAt(eye,target),proj=perspective(.9,canvas.width/canvas.height,.2,2000),m=matMul(proj,view);gl.useProgram(prog);gl.uniformMatrix4fv(prog.m,false,m);gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.enableVertexAttribArray(prog.p);gl.vertexAttribPointer(prog.p,3,gl.FLOAT,false,0,0);/* rebuild normals/colors from a coarse procedural assumption for props; terrain retains geometry but uses shader defaults */
const nbuf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,nbuf);const ns=new Float32Array(count*3);for(let i=0;i<ns.length;i+=9){ns[i]=0;ns[i+1]=1;ns[i+2]=0;ns[i+3]=0;ns[i+4]=1;ns[i+5]=0;ns[i+6]=0;ns[i+7]=1;ns[i+8]=0}gl.bufferData(gl.ARRAY_BUFFER,ns,gl.STATIC_DRAW);gl.enableVertexAttribArray(prog.n);gl.vertexAttribPointer(prog.n,3,gl.FLOAT,false,0,0);const cb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,cb);const cs=new Float32Array(count*3);for(let i=0;i<cs.length;i+=3){cs[i]=.28;cs[i+1]=.50;cs[i+2]=.21}gl.bufferData(gl.ARRAY_BUFFER,cs,gl.STATIC_DRAW);gl.enableVertexAttribArray(prog.c);gl.vertexAttribPointer(prog.c,3,gl.FLOAT,false,0,0);gl.drawArrays(gl.TRIANGLES,0,count)}
let last=performance.now();function loop(t){const dt=Math.min(.04,(t-last)/1000);last=t;if(active()){move(dt);pickupCheck();updatePrompt();draw()}requestAnimationFrame(loop)}load();loop(last);
})();