(()=>{'use strict';
const game=document.getElementById('game');if(!game)return;
const old=game.querySelector('#world');if(old)old.style.display='none';
const style=document.createElement('style');style.textContent=`#battleCanvas{position:absolute;inset:0;width:100%;height:100%;z-index:2;background:linear-gradient(#68c8ef 0%,#cfeef5 58%,#79a75e 100%)}.battleHud{position:absolute;inset:0;z-index:12;pointer-events:none;font-family:Arial,sans-serif}.bhBox{position:absolute;background:#101a2ddd;border:1px solid #ffffff26;box-shadow:0 4px 12px #0005;padding:9px 12px;font-weight:900}.bhStats{left:14px;top:14px;width:250px}.bhAmmo{right:14px;top:14px;text-align:right;min-width:175px}.bhPrompt{left:50%;bottom:18px;transform:translateX(-50%);white-space:nowrap}.bhCross{position:absolute;left:50%;top:50%;width:18px;height:18px;transform:translate(-50%,-50%)}.bhCross:before,.bhCross:after{content:'';position:absolute;background:#fff}.bhCross:before{left:8px;width:2px;height:18px}.bhCross:after{top:8px;width:18px;height:2px}.bhBar{height:8px;background:#17263b;margin-top:6px;border-radius:3px;overflow:hidden}.bhBar i{display:block;height:100%;background:#58df86}.bhShield i{background:#57c6ff}.bhSmall{font-size:10px;color:#bfd0df}.bhLoot{color:#ffd94e;margin-top:6px}.bhStorm{right:14px;top:82px;width:210px}.bhStorm b{color:#eaa8ff}.bhFeed{right:14px;bottom:18px;text-align:right;font-size:11px;line-height:1.5;max-width:310px}`;document.head.appendChild(style);
const canvas=document.createElement('canvas');canvas.id='battleCanvas';game.insertBefore(canvas,game.firstChild);
const hud=document.createElement('div');hud.className='battleHud';hud.innerHTML=`<div class="bhBox bhStats"><div>SOLO · 100 PLAYERS</div><div class="bhSmall">STORMRUNNER</div><div class="bhBar"><i id="bhHp" style="width:100%"></i></div><div class="bhBar bhShield"><i id="bhShield" style="width:50%"></i></div><div class="bhLoot" id="bhLoot">ASSAULT RIFLE · 30 / 120</div></div><div class="bhBox bhAmmo"><div id="bhWeapon">ASSAULT RIFLE</div><strong id="bhAmmo">30</strong> / 120</div><div class="bhBox bhStorm">STORM <b id="bhStormTimer">00:55</b><br><span class="bhSmall" id="bhStormState">SAFE ZONE</span></div><div class="bhCross"></div><div class="bhBox bhPrompt" id="bhPrompt">WASD move · SHIFT sprint · SPACE jump · E search chest · Q build</div><div class="bhBox bhFeed" id="bhFeed">LANDED ON ISLAND</div>`;game.appendChild(hud);
let gl,prog,loaded=false,loading=false;let posBuf,normBuf,colBuf,count=0;const terrain=[];const world={min:-330,max:330,n:150,cell:4.45};let heights=null;const player={x:0,y:0,z:170,vy:0,onGround:false,yaw:0,pitch:.10,hp:100,shield:50,ammo:30,maxAmmo:120,weapon:'ASSAULT RIFLE',kills:0};const keys={};let camYaw=0,camPitch=.16,camDist=8;let houses=[],chests=[],pickups=[],bots=[],builds=[];let stormRadius=330,stormTimer=55,stormActive=false,lastShot=0;
const q=id=>document.getElementById(id),prompt=t=>q('bhPrompt').textContent=t,feed=t=>q('bhFeed').textContent=t;
addEventListener('keydown',e=>{if(e.repeat)return;keys[e.code]=1;if(e.code==='KeyE')openChest();if(e.code==='KeyQ')buildWall()});addEventListener('keyup',e=>keys[e.code]=0);
canvas.addEventListener('click',()=>canvas.requestPointerLock?.());addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas){camYaw-=e.movementX*.0024;camPitch=Math.max(-.38,Math.min(.48,camPitch-e.movementY*.0016));}});addEventListener('mousedown',e=>{if(document.pointerLockElement===canvas&&e.button===0)shoot()});
function resize(){const d=Math.min(2,devicePixelRatio||1);canvas.width=Math.max(1,innerWidth*d);canvas.height=Math.max(1,innerHeight*d);if(gl)gl.viewport(0,0,canvas.width,canvas.height)}addEventListener('resize',resize);resize();
function sh(t,s){const z=gl.createShader(t);gl.shaderSource(z,s);gl.compileShader(z);if(!gl.getShaderParameter(z,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(z));return z}
function initGL(){gl=canvas.getContext('webgl',{antialias:true,alpha:false,preserveDrawingBuffer:false});if(!gl)throw Error('WebGL unavailable');const vs=`attribute vec3 aP;attribute vec3 aN;attribute vec3 aC;uniform mat4 uM;varying vec3 vC;varying float vL;void main(){gl_Position=uM*vec4(aP,1.0);vC=aC;vL=.48+.52*max(dot(normalize(aN),normalize(vec3(-.45,.88,.28))),0.0);}`;const fs=`precision mediump float;varying vec3 vC;varying float vL;void main(){gl_FragColor=vec4(vC*vL,1.0);}`;prog=gl.createProgram();gl.attachShader(prog,sh(gl.VERTEX_SHADER,vs));gl.attachShader(prog,sh(gl.FRAGMENT_SHADER,fs));gl.linkProgram(prog);if(!gl.getProgramParameter(prog,gl.LINK_STATUS))throw Error('shader link failed');prog.p=gl.getAttribLocation(prog,'aP');prog.n=gl.getAttribLocation(prog,'aN');prog.c=gl.getAttribLocation(prog,'aC');prog.m=gl.getUniformLocation(prog,'uM');gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.cullFace(gl.BACK);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA)}
function perspective(f,a,n,far){const f2=1/Math.tan(f/2),nf=1/(n-far);return new Float32Array([f2/a,0,0,0,0,f2,0,0,0,0,(far+n)*nf,-1,0,0,2*far*n*nf,0])}
function lookAt(e,t,u=[0,1,0]){let zx=e[0]-t[0],zy=e[1]-t[1],zz=e[2]-t[2],l=Math.hypot(zx,zy,zz)||1;zx/=l;zy/=l;zz/=l;let xx=u[1]*zz-u[2]*zy,xy=u[2]*zx-u[0]*zz,xz=u[0]*zy-u[1]*zx,l2=Math.hypot(xx,xy,xz)||1;xx/=l2;xy/=l2;xz/=l2;const yx=zy*xz-zz*xy,yy=zz*xx-zx*xz,yz=zx*xy-zy*xx;return new Float32Array([xx,yx,zx,0,xy,yy,zy,0,xz,yz,zz,0,-(xx*e[0]+xy*e[1]+xz*e[2]),-(yx*e[0]+yy*e[1]+yz*e[2]),-(zx*e[0]+zy*e[1]+zz*e[2]),1])}
function mul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o}
function hidx(gx,gz){return gz*world.n+gx}function sampleHeight(x,z){if(!heights)return 0;const fx=(x-world.min)/(world.max-world.min)*(world.n-1),fz=(z-world.min)/(world.max-world.min)*(world.n-1);const x0=Math.max(0,Math.min(world.n-1,Math.floor(fx))),z0=Math.max(0,Math.min(world.n-1,Math.floor(fz))),x1=Math.min(world.n-1,x0+1),z1=Math.min(world.n-1,z0+1),tx=Math.max(0,Math.min(1,fx-x0)),tz=Math.max(0,Math.min(1,fz-z0));const a=heights[hidx(x0,z0)],b=heights[hidx(x1,z0)],c=heights[hidx(x0,z1)],d=heights[hidx(x1,z1)];return a+(b-a)*tx+((c+(d-c)*tx)- (a+(b-a)*tx))*tz}
function groundAt(x,z){return sampleHeight(Math.max(world.min,Math.min(world.max,x)),Math.max(world.min,Math.min(world.max,z)))}
function tri(a,b,c,col){const ux=b[0]-a[0],uy=b[1]-a[1],uz=b[2]-a[2],vx=c[0]-a[0],vy=c[1]-a[1],vz=c[2]-a[2],nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx,l=Math.hypot(nx,ny,nz);if(!Number.isFinite(l)||l<.0001)return;for(const p of[a,b,c]){terrain.push(...p);terrain.push(nx/l,ny/l,nz/l);terrain.push(...col)}}
const G={p:[],n:[],c:[]};function addTri(a,b,c,col){const ux=b[0]-a[0],uy=b[1]-a[1],uz=b[2]-a[2],vx=c[0]-a[0],vy=c[1]-a[1],vz=c[2]-a[2],nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx,l=Math.hypot(nx,ny,nz);if(!Number.isFinite(l)||l<.0001)return;for(const p of[a,b,c]){G.p.push(...p);G.n.push(nx/l,ny/l,nz/l);G.c.push(...col)}}
function box(x0,y0,z0,x1,y1,z1,col){const v=[[x0,y0,z0],[x1,y0,z0],[x1,y1,z0],[x0,y1,z0],[x0,y0,z1],[x1,y0,z1],[x1,y1,z1],[x0,y1,z1]];addTri(v[0],v[1],v[2],col);addTri(v[0],v[2],v[3],col);addTri(v[4],v[6],v[5],col);addTri(v[4],v[7],v[6],col);addTri(v[0],v[4],v[5],col);addTri(v[0],v[5],v[1],col);addTri(v[3],v[2],v[6],col);addTri(v[3],v[6],v[7],col);addTri(v[1],v[5],v[6],col);addTri(v[1],v[6],v[2],col);addTri(v[0],v[3],v[7],col);addTri(v[0],v[7],v[4],col)}
function house(x,z,s){const y=groundAt(x,z);houses.push({x,z,y,s});box(x-8*s,y,z-7*s,x+8*s,y+8*s,z+7*s,[.69,.49,.31]);box(x-9*s,y+8*s,z-8*s,x+9*s,y+14*s,z+8*s,[.40,.10,.09]);box(x-2.5*s,y+1,z-7.3*s,x+2.5*s,y+6,z-7.0*s,[.12,.27,.34]);box(x-7*s,y+2,z+7.2*s,x-3*s,y+6,z+7.4*s,[.16,.50,.72]);box(x+3*s,y+2,z+7.2*s,x+7*s,y+6,z+7.4*s,[.16,.50,.72])}
function chest(x,z){const y=groundAt(x,z)+1.3;const c={x,z,y,open:false};chests.push(c);box(x-1.8,y-.9,z-.9,x+1.8,y+.6,z+.9,[.52,.30,.06]);box(x-1.8,y+.6,z-.9,x+1.8,y+1.5,z+.9,[.90,.67,.10]);}
function pickup(x,z,type){const y=groundAt(x,z)+1.1;const p={x,z,y,type,taken:false};pickups.push(p);box(x-.65,y-.4,z-.65,x+.65,y+.4,z+.65,type==='ammo'?[.95,.81,.10]:type==='shield'?[.08,.57,.98]:[.86,.13,.70])}
function bot(x,z){const y=groundAt(x,z);bots.push({x,z,y,hp:100,cd:0});box(x-1,y,z-1,x+1,y+4,z+1,[.86,.19,.22]);box(x-1.25,y+4,z-1.25,x+1.25,y+6,z+1.25,[.92,.72,.43])}
function addTree(x,z){const y=groundAt(x,z);box(x-.6,y,z-.6,x+.6,y+7,z+.6,[.30,.20,.10]);box(x-3,y+5,z-3,x+3,y+10,z+3,[.08,.36,.16]);box(x-2.2,y+8,z-2.2,x+2.2,y+12,z+2.2,[.10,.45,.20])}
async function load(){if(loading||loaded)return;loading=true;try{initGL();const r=await fetch('fnscan.obj',{cache:'no-store'});if(!r.ok)throw Error('fnscan.obj not found');const text=await r.text(),lines=text.split(/\r?\n/),V=[],mn=[Infinity,Infinity,Infinity],mx=[-Infinity,-Infinity,-Infinity];for(const line of lines){if(!line.startsWith('v '))continue;const a=line.trim().split(/\s+/),x=Number(a[1]),y=Number(a[2]),z=Number(a[3]);if(![x,y,z].every(Number.isFinite))continue;V.push(x,y,z);mn[0]=Math.min(mn[0],x);mn[1]=Math.min(mn[1],y);mn[2]=Math.min(mn[2],z);mx[0]=Math.max(mx[0],x);mx[1]=Math.max(mx[1],y);mx[2]=Math.max(mx[2],z)}if(!V.length)throw Error('OBJ has no valid vertices');const xr=mx[0]-mn[0]||1,zr=mx[2]-mn[2]||1,yr=mx[1]-mn[1]||1,sxy=620/Math.max(xr,zr),sy=170/yr;heights=new Float32Array(world.n*world.n);const seen=new Uint8Array(world.n*world.n),INF=1e9;heights.fill(INF);for(let i=0;i<V.length;i+=3){const x=(V[i]-(mn[0]+mx[0])/2)*sxy,z=(V[i+2]-(mn[2]+mx[2])/2)*sxy,y=(V[i+1]-mn[1])*sy;const gx=Math.max(0,Math.min(world.n-1,Math.round((x-world.min)/(world.max-world.min)*(world.n-1)))),gz=Math.max(0,Math.min(world.n-1,Math.round((z-world.min)/(world.max-world.min)*(world.n-1)))),gi=hidx(gx,gz);if(!seen[gi]||y<heights[gi]){heights[gi]=y;seen[gi]=1}}for(let pass=0;pass<5;pass++){for(let z=0;z<world.n;z++)for(let x=0;x<world.n;x++){const gi=hidx(x,z);if(seen[gi])continue;let sum=0,n=0;for(let dz=-2;dz<=2;dz++)for(let dx=-2;dx<=2;dx++){if(!dx&&!dz)continue;const xx=x+dx,zz=z+dz;if(xx>=0&&xx<world.n&&zz>=0&&zz<world.n){const j=hidx(xx,zz);if(seen[j]){sum+=heights[j];n++}}}if(n){heights[gi]=sum/n;seen[gi]=1}}}let fallback=20;for(let i=0;i<heights.length;i++)if(!Number.isFinite(heights[i]))heights[i]=fallback;
G.p.length=0;G.n.length=0;G.c.length=0;for(let gz=0;gz<world.n-1;gz++){for(let gx=0;gx<world.n-1;gx++){const x0=world.min+(world.max-world.min)*gx/(world.n-1),x1=world.min+(world.max-world.min)*(gx+1)/(world.n-1),z0=world.min+(world.max-world.min)*gz/(world.n-1),z1=world.min+(world.max-world.min)*(gz+1)/(world.n-1),h00=heights[hidx(gx,gz)],h10=heights[hidx(gx+1,gz)],h01=heights[hidx(gx,gz+1)],h11=heights[hidx(gx+1,gz+1)];const A=[x0,h00,z0],B=[x1,h10,z0],C=[x1,h11,z1],D=[x0,h01,z1];const avg=(h00+h10+h01+h11)/4,col=avg>120?[.55,.58,.38]:avg<18?[.17,.38,.17]:[.25,.51,.23];addTri(A,B,C,col);addTri(A,C,D,col)}}
for(let x=-270;x<=270;x+=90)for(let z=-270;z<=270;z+=90){const jitter=((x*13+z*7)%23)-11;if(Math.hypot(x+jitter,z-jitter)>120&&((x/90+z/90)%2===0))house(x+jitter,z-jitter,.85+(((x+z)%3+3)%3)*.08)}
for(const h of houses){chest(h.x+Math.min(6,h.s*4),h.z+Math.min(6,h.s*4));pickup(h.x-5,h.z,'ammo')}for(let x=-220;x<=220;x+=110)for(let z=-220;z<=220;z+=110)if(Math.hypot(x,z)>90){addTree(x+13,z-9);bot(x-15,z+10)}
for(let i=0;i<7;i++){const a=i*Math.PI*2/7+0.2;pickup(Math.cos(a)*110,Math.sin(a)*110,i%3===0?'shield':'ammo')}
for(let i=0;i<7;i++){const a=i*Math.PI*2/7;bot(Math.cos(a)*230,Math.sin(a)*230)}
const mk=(arr)=>{const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(arr),gl.STATIC_DRAW);return b};posBuf=mk(G.p);normBuf=mk(G.n);colBuf=mk(G.c);count=G.p.length/3;loaded=true;player.x=0;player.z=170;player.y=groundAt(player.x,player.z)+1.75;player.onGround=true;feed('LANDED · ISLAND READY');}catch(e){console.error(e);feed('MAP ERROR · '+e.message);loaded=true;heights=new Float32Array(world.n*world.n);heights.fill(8);G.p=[];G.n=[];G.c=[];for(let z=0;z<world.n-1;z++)for(let x=0;x<world.n-1;x++){const x0=world.min+(world.max-world.min)*x/(world.n-1),x1=world.min+(world.max-world.min)*(x+1)/(world.n-1),z0=world.min+(world.max-world.min)*z/(world.n-1),z1=world.min+(world.max-world.min)*(z+1)/(world.n-1);addTri([x0,8,z0],[x1,8,z0],[x1,8,z1],[.25,.5,.22]);addTri([x0,8,z0],[x1,8,z1],[x0,8,z1],[.25,.5,.22])}posBuf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,posBuf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(G.p),gl.STATIC_DRAW);normBuf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,normBuf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(G.n),gl.STATIC_DRAW);colBuf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,colBuf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(G.c),gl.STATIC_DRAW);count=G.p.length/3;player.y=10}}
function openChest(){let best=null,bd=999;for(const c of chests)if(!c.open){const d=Math.hypot(player.x-c.x,player.z-c.z);if(d<bd){bd=d;best=c}}if(!best||bd>8){prompt('WASD move · E search chest when nearby');return}best.open=true;const t=Math.random();if(t<.55){player.ammo=Math.min(player.maxAmmo,player.ammo+30);feed('CHEST FOUND · AMMO +30')}else{player.shield=Math.min(100,player.shield+30);feed('CHEST FOUND · SHIELD +30')}prompt('WASD move · SHIFT sprint · SPACE jump · Q build')}
function buildWall(){const ang=camYaw;const bx=player.x+Math.sin(ang)*6,bz=player.z+Math.cos(ang)*6,by=groundAt(bx,bz);builds.push({x:bx,y:by,z:bz,a:ang,life:20});feed('BUILD WALL · Q');}
function shoot(){const now=performance.now();if(now-lastShot<180||player.ammo<=0)return;lastShot=now;player.ammo--;let best=null,bd=999;const dx=Math.sin(camYaw),dz=Math.cos(camYaw);for(const b of bots){if(b.hp<=0)continue;const vx=b.x-player.x,vz=b.z-player.z,d=Math.hypot(vx,vz);if(d>55)continue;const dot=(vx*dx+vz*dz)/(d||1);if(dot>.94&&d<bd){bd=d;best=b}}if(best){best.hp-=40;if(best.hp<=0){player.kills++;feed('ELIMINATED BOT · '+player.kills);if(Math.random()<.7)pickup(best.x,best.z,'ammo')}}}
function update(dt){if(!loaded)return;let f=0,r=0;if(keys.KeyW)f++;if(keys.KeyS)f--;if(keys.KeyA)r--;if(keys.KeyD)r++;const len=Math.hypot(f,r)||1,spd=(keys.ShiftLeft||keys.ShiftRight)?62:38,s=Math.sin(player.yaw),c=Math.cos(player.yaw);player.x+=(r*c+f*s)/len*spd*dt;player.z+=(f*c-r*s)/len*spd*dt;player.x=Math.max(world.min+5,Math.min(world.max-5,player.x));player.z=Math.max(world.min+5,Math.min(world.max-5,player.z));player.y=groundAt(player.x,player.z)+1.75;if(keys.Space&&player.onGround){player.vy=17;player.onGround=false}if(!player.onGround){player.vy-=42*dt;player.y+=player.vy*dt;const gy=groundAt(player.x,player.z)+1.75;if(player.y<=gy){player.y=gy;player.vy=0;player.onGround=true}}player.yaw=camYaw;
for(const p of pickups)if(!p.taken&&Math.hypot(player.x-p.x,player.z-p.z)<3){p.taken=true;if(p.type==='ammo')player.ammo=Math.min(player.maxAmmo,player.ammo+30);else player.shield=Math.min(100,player.shield+25);feed(p.type==='ammo'?'AMMO +30':'SHIELD +25')}
for(const b of bots){if(b.hp<=0)continue;b.cd-=dt;const dx=player.x-b.x,dz=player.z-b.z,d=Math.hypot(dx,dz);if(d<38){b.x+=(dx/(d||1))*7*dt;b.z+=(dz/(d||1))*7*dt;if(b.cd<=0){b.cd=1.7;if(player.shield>0)player.shield=Math.max(0,player.shield-8);else player.hp=Math.max(0,player.hp-8)}}}
for(const b of builds)b.life-=dt;builds=builds.filter(b=>b.life>0);stormTimer-=dt;if(stormTimer<=0){stormActive=true;stormRadius=Math.max(65,stormRadius-10*dt);q('bhStormState').textContent='STORM SHRINKING'}if(stormActive&&Math.hypot(player.x,player.z)>stormRadius){player.hp=Math.max(0,player.hp-9*dt)}if(player.hp<=0){feed('YOU WERE ELIMINATED · returning to lobby');setTimeout(()=>location.reload(),1600)}
q('bhHp').style.width=player.hp+'%';q('bhShield').style.width=player.shield+'%';q('bhAmmo').textContent=player.ammo;q('bhLoot').textContent=player.weapon+' · '+player.ammo+' / '+player.maxAmmo;q('bhStormTimer').textContent=Math.max(0,Math.ceil(stormTimer)).toString().padStart(2,'0')+':'+Math.floor((stormTimer%1)*60).toString().padStart(2,'0');}
function draw(){if(!loaded||!gl)return;gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(.28,.68,.84,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const cp=Math.cos(camPitch),sp=Math.sin(camPitch),sy=Math.sin(camYaw),cy=Math.cos(camYaw),front=[sy*cp,sp,cy*cp],eye=[player.x-front[0]*camDist,player.y+2.5-front[1]*camDist,player.z-front[2]*camDist],target=[player.x,player.y+1.1,player.z],proj=perspective(1.02,canvas.width/canvas.height,.2,1600),m=mul(proj,lookAt(eye,target));gl.useProgram(prog);gl.uniformMatrix4fv(prog.m,false,m);gl.bindBuffer(gl.ARRAY_BUFFER,posBuf);gl.enableVertexAttribArray(prog.p);gl.vertexAttribPointer(prog.p,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,normBuf);gl.enableVertexAttribArray(prog.n);gl.vertexAttribPointer(prog.n,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,colBuf);gl.enableVertexAttribArray(prog.c);gl.vertexAttribPointer(prog.c,3,gl.FLOAT,false,0,0);gl.drawArrays(gl.TRIANGLES,0,count);
function extraBox(x,y,z,sx,sy,sz,col){const saveP=G.p,saveN=G.n,saveC=G.c;G.p=[];G.n=[];G.c=[];box(x-sx,y,z-sz,x+sx,y+sy,z+sz,col);const pb=gl.createBuffer(),nb=gl.createBuffer(),cb=gl.createBuffer();const drawN=G.p.length/3;gl.bindBuffer(gl.ARRAY_BUFFER,pb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(G.p),gl.STREAM_DRAW);gl.enableVertexAttribArray(prog.p);gl.vertexAttribPointer(prog.p,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,nb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(G.n),gl.STREAM_DRAW);gl.enableVertexAttribArray(prog.n);gl.vertexAttribPointer(prog.n,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,cb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(G.c),gl.STREAM_DRAW);gl.enableVertexAttribArray(prog.c);gl.vertexAttribPointer(prog.c,3,gl.FLOAT,false,0,0);gl.drawArrays(gl.TRIANGLES,0,drawN);gl.deleteBuffer(pb);gl.deleteBuffer(nb);gl.deleteBuffer(cb);G.p=saveP;G.n=saveN;G.c=saveC}
for(const h of houses)extraBox(h.x,h.y+15,h.z,h.s*8,.4,h.s*8,[.04,.04,.05]);
for(const c of chests)if(!c.open)extraBox(c.x,c.y+.2,c.z,1.8,.4,.8,[.95,.70,.12]);
for(const p of pickups)if(!p.taken)extraBox(p.x,p.y,p.z,.7,.7,.7,p.type==='ammo'?[.95,.80,.12]:[.10,.70,.98]);
for(const b of bots)if(b.hp>0){extraBox(b.x,b.y+1.0,b.z,1.05,5.0,1.05,[.82,.18,.22]);extraBox(b.x,b.y+5.1,b.z,1.3,1.3,1.3,[.95,.71,.45])}
for(const b of builds)extraBox(b.x,b.y,b.z,.18,6,.18,[.72,.46,.22]);}
let last=performance.now();(function loop(t){const dt=Math.min(.05,(t-last)/1000);last=t;if(!game.classList.contains('hidden')&&getComputedStyle(game).display!=='none'){if(!loaded)load();update(dt);draw()}requestAnimationFrame(loop)})(last);load();
})();