(()=>{'use strict';
const game=document.getElementById('game'),oldCanvas=document.getElementById('world');if(!game)return;
const css=document.createElement('style');css.textContent='#objMap{position:absolute;inset:0;width:100%;height:100%;z-index:2;background:linear-gradient(#73c9ef,#dff4fb 60%,#74a65f)}#objLoad{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);z-index:20;padding:22px 28px;background:#101a2ddd;border:1px solid #fff3;text-align:center;font-weight:900;min-width:340px;border-radius:8px}#objBar{height:9px;background:#fff2;margin-top:10px}#objBar i{display:block;height:100%;width:0;background:#f4cf49}#objReady{position:absolute;left:50%;bottom:78px;transform:translateX(-50%);z-index:25;padding:10px 16px;background:#17233de8;border:1px solid #fff3;font-weight:900}';document.head.appendChild(css);
const c=document.createElement('canvas');c.id='objMap';game.insertBefore(c,game.firstChild);const load=document.createElement('div');load.id='objLoad';load.innerHTML='<div id="objStatus">LOADING 3D ISLAND</div><div id="objBar"><i></i></div><small id="objDetail">Reading fnscan.obj…</small>';game.appendChild(load);const ready=document.createElement('div');ready.id='objReady';ready.textContent='3D ISLAND READY';ready.style.display='none';game.appendChild(ready);
let gl,prog,pb,nb,count=0,loaded=false,loading=false;const pos={x:0,y:140,z:0,yaw:0,pitch:-.38};const keys={};let drag=false,lx=0,ly=0,dist=260,center=[0,0,0],scale=1,bounds=[-450,450,-120,520,-450,450];
addEventListener('keydown',e=>keys[e.code]=1);addEventListener('keyup',e=>keys[e.code]=0);c.onmousedown=e=>{drag=true;lx=e.clientX;ly=e.clientY;c.style.cursor='grabbing'};addEventListener('mouseup',()=>{drag=false;c.style.cursor='grab'});addEventListener('mousemove',e=>{if(!drag)return;pos.yaw-=(e.clientX-lx)*.008;pos.pitch=Math.max(-1.25,Math.min(.45,pos.pitch-(e.clientY-ly)*.006));lx=e.clientX;ly=e.clientY});c.onwheel=e=>{dist=Math.max(90,Math.min(520,dist+e.deltaY*.12));};
function resize(){const d=Math.min(2,devicePixelRatio||1);c.width=innerWidth*d;c.height=innerHeight*d;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';if(gl)gl.viewport(0,0,c.width,c.height)}addEventListener('resize',resize);resize();
function sh(t,s){const q=gl.createShader(t);gl.shaderSource(q,s);gl.compileShader(q);if(!gl.getShaderParameter(q,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(q));return q}
function init(){gl=c.getContext('webgl',{antialias:true,alpha:false,preserveDrawingBuffer:false});if(!gl)throw Error('WebGL unavailable');const vs=`attribute vec3 p;attribute vec3 n;uniform mat4 uMVP;varying float vL;varying float vH;void main(){gl_Position=uMVP*vec4(p,1.0);vL=.45+.55*max(dot(normalize(n),normalize(vec3(-.35,.85,.3))),0.0);vH=p.y;}`;const fs=`precision mediump float;varying float vL;varying float vH;void main(){float h=clamp(vH*.0012+.5,0.0,1.0);vec3 low=vec3(.10,.27,.12),mid=vec3(.28,.50,.21),high=vec3(.63,.68,.44);vec3 c=mix(low,mid,smoothstep(0.0,.55,h));c=mix(c,high,smoothstep(.55,1.0,h));gl_FragColor=vec4(c*vL,1.0);}`;prog=gl.createProgram();gl.attachShader(prog,sh(gl.VERTEX_SHADER,vs));gl.attachShader(prog,sh(gl.FRAGMENT_SHADER,fs));gl.linkProgram(prog);if(!gl.getProgramParameter(prog,gl.LINK_STATUS))throw Error('shader link failed');prog.p=gl.getAttribLocation(prog,'p');prog.n=gl.getAttribLocation(prog,'n');prog.mvp=gl.getUniformLocation(prog,'uMVP');gl.enable(gl.DEPTH_TEST);gl.clearDepth(1);gl.enable(gl.CULL_FACE);gl.cullFace(gl.BACK)}
function perspective(fovy,aspect,near,far){const f=1/Math.tan(fovy/2),nf=1/(near-far);return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,(2*far*near)*nf,0])}
function lookAt(e,t,u){let zx=e[0]-t[0],zy=e[1]-t[1],zz=e[2]-t[2],zl=Math.hypot(zx,zy,zz)||1;zx/=zl;zy/=zl;zz/=zl;let xx=u[1]*zz-u[2]*zy,xy=u[2]*zx-u[0]*zz,xz=u[0]*zy-u[1]*zx,xl=Math.hypot(xx,xy,xz)||1;xx/=xl;xy/=xl;xz/=xl;let yx=zy*xz-zz*xy,yy=zz*xx-zx*xz,yz=zx*xy-zy*xx;return new Float32Array([xx,yx,zx,0,xy,yy,zy,0,xz,yz,zz,0,-(xx*e[0]+xy*e[1]+xz*e[2]),-(yx*e[0]+yy*e[1]+yz*e[2]),-(zx*e[0]+zy*e[1]+zz*e[2]),1])}
function mul(a,b){const o=new Float32Array(16);for(let col=0;col<4;col++)for(let row=0;row<4;row++)o[col*4+row]=a[row]*b[col*4]+a[4+row]*b[col*4+1]+a[8+row]*b[col*4+2]+a[12+row]*b[col*4+3];return o}
async function loadOBJ(){if(loading||loaded)return;loading=true;try{init();const r=await fetch('fnscan.obj',{cache:'no-store'});if(!r.ok)throw Error('fnscan.obj not found');const text=await r.text();const V=[],P=[],N=[],mn=[Infinity,Infinity,Infinity],mx=[-Infinity,-Infinity,-Infinity],lines=text.split(/\r?\n/);document.getElementById('objDetail').textContent='Scanning bounds…';for(const line of lines){if(line.startsWith('v ')){const a=line.trim().split(/\s+/),x=+a[1],y=+a[2],z=+a[3];V.push(x,y,z);if(x<mn[0])mn[0]=x;if(y<mn[1])mn[1]=y;if(z<mn[2])mn[2]=z;if(x>mx[0])mx[0]=x;if(y>mx[1])mx[1]=y;if(z>mx[2])mx[2]=z}}
center=[(mn[0]+mx[0])/2,(mn[1]+mx[1])/2,(mn[2]+mx[2])/2];scale=700/Math.max(mx[0]-mn[0],mx[1]-mn[1],mx[2]-mn[2]);bounds=[-350,350,(mn[1]-center[1])*scale-10,(mx[1]-center[1])*scale+10,-350,350];
for(let i=0;i<lines.length;i++){const line=lines[i];if(!line.startsWith('f '))continue;const ids=line.trim().split(/\s+/).slice(1).map(s=>{const n=parseInt(s.split('/')[0],10);return n<0?V.length/3+n:n-1});for(let k=1;k<ids.length-1;k++){const tri=[ids[0],ids[k],ids[k+1]],a=[],nrm=[0,0,0];for(const id of tri)a.push([ (V[id*3]-center[0])*scale,(V[id*3+1]-center[1])*scale,(V[id*3+2]-center[2])*scale ]);const ux=a[1][0]-a[0][0],uy=a[1][1]-a[0][1],uz=a[1][2]-a[0][2],vx=a[2][0]-a[0][0],vy=a[2][1]-a[0][1],vz=a[2][2]-a[0][2];nrm[0]=uy*vz-uz*vy;nrm[1]=uz*vx-ux*vz;nrm[2]=ux*vy-uy*vx;const nl=Math.hypot(...nrm)||1;for(const q of a){P.push(...q);N.push(nrm[0]/nl,nrm[1]/nl,nrm[2]/nl)}}if((i%2500)===0){const pct=Math.min(99,Math.round(i/lines.length*100));document.querySelector('#objBar i').style.width=pct+'%';document.getElementById('objDetail').textContent='Building island mesh… '+pct+'%';await new Promise(r=>setTimeout(r,0))}}
pb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,pb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(P),gl.STATIC_DRAW);nb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,nb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(N),gl.STATIC_DRAW);count=P.length/3;loaded=true;load.style.display='none';ready.style.display='block';setTimeout(()=>ready.style.display='none',1800);if(oldCanvas)oldCanvas.style.display='none';pos.x=0;pos.z=260;pos.y=340;pos.pitch=-.52;dist=330}catch(e){document.getElementById('objStatus').textContent='3D MAP ERROR';document.getElementById('objDetail').textContent=e.message;console.error(e)}}
function active(){return !game.classList.contains('hidden')&&getComputedStyle(game).display!=='none'}
const mo=new MutationObserver(()=>{if(active()){if(oldCanvas)oldCanvas.style.display='none';if(!loaded)loadOBJ()}else{if(oldCanvas)oldCanvas.style.display='block';load.style.display='none'}});mo.observe(game,{attributes:true,attributeFilter:['class','style']});
function update(dt){if(!active())return;let sp=(keys.ShiftLeft||keys.ShiftRight)?130:75,s=Math.sin(pos.yaw),c=Math.cos(pos.yaw),f=0,r=0;if(keys.KeyW)f++;if(keys.KeyS)f--;if(keys.KeyA)r--;if(keys.KeyD)r++;const l=Math.hypot(f,r)||1;pos.x+=(r*c+f*s)/l*sp*dt;pos.z+=(f*c-r*s)/l*sp*dt;if(keys.Space)pos.y+=85*dt;if(keys.ControlLeft||keys.ControlRight)pos.y-=110*dt;pos.x=Math.max(bounds[0],Math.min(bounds[1],pos.x));pos.z=Math.max(bounds[4],Math.min(bounds[5],pos.z));pos.y=Math.max(Math.max(12,bounds[2]),Math.min(bounds[3]+220,pos.y))}
function draw(){if(!active()||!gl||!loaded)return;gl.viewport(0,0,c.width,c.height);gl.clearColor(.34,.70,.86,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const cp=Math.cos(pos.pitch),sp=Math.sin(pos.pitch),sy=Math.sin(pos.yaw),cy=Math.cos(pos.yaw),front=[sy*cp,sp,cy*cp],eye=[pos.x-front[0]*dist,pos.y-front[1]*dist,pos.z-front[2]*dist],target=[pos.x,pos.y-25,pos.z],view=lookAt(eye,target,[0,1,0]),proj=perspective(1.0,c.width/c.height,.5,5000),m=mul(proj,view);gl.useProgram(prog);gl.uniformMatrix4fv(prog.mvp,false,m);gl.bindBuffer(gl.ARRAY_BUFFER,pb);gl.enableVertexAttribArray(prog.p);gl.vertexAttribPointer(prog.p,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,nb);gl.enableVertexAttribArray(prog.n);gl.vertexAttribPointer(prog.n,3,gl.FLOAT,false,0,0);gl.drawArrays(gl.TRIANGLES,0,count)}
let last=performance.now();(function loop(t){const dt=Math.min(.05,(t-last)/1000);last=t;update(dt);draw();requestAnimationFrame(loop)})(last);loadOBJ();})();