(()=>{'use strict';
const game=document.getElementById('game'),oldCanvas=document.getElementById('world');if(!game)return;
const css=document.createElement('style');css.textContent='#objMap{position:absolute;inset:0;width:100%;height:100%;z-index:2;background:#79ccec}#objLoad{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);z-index:5;padding:22px 28px;background:#101a2ddd;border:1px solid #fff3;text-align:center;font-weight:900;min-width:320px}#objBar{height:8px;background:#fff2;margin-top:10px}#objBar i{display:block;height:100%;width:0;background:#f4cf49}';document.head.appendChild(css);
const c=document.createElement('canvas');c.id='objMap';game.insertBefore(c,game.firstChild);const load=document.createElement('div');load.id='objLoad';load.innerHTML='<div id="objStatus">LOADING 3D ISLAND</div><div id="objBar"><i></i></div><small id="objDetail">Reading fnscan.obj…</small>';game.appendChild(load);
let gl,prog,pb,nb,count=0,loaded=false,loading=false;const pos={x:0,y:45,z:0,yaw:0,pitch:-.22};const keys={};let drag=false,lx=0,ly=0,dist=180;
addEventListener('keydown',e=>keys[e.code]=1);addEventListener('keyup',e=>keys[e.code]=0);c.onmousedown=e=>{drag=true;lx=e.clientX;ly=e.clientY;c.style.cursor='grabbing'};addEventListener('mouseup',()=>{drag=false;c.style.cursor='grab'});addEventListener('mousemove',e=>{if(!drag)return;pos.yaw-=(e.clientX-lx)*.008;pos.pitch=Math.max(-1.1,Math.min(.5,pos.pitch-(e.clientY-ly)*.006));lx=e.clientX;ly=e.clientY});c.onwheel=e=>{dist=Math.max(70,Math.min(360,dist+e.deltaY*.08));};
function resize(){c.width=innerWidth*(devicePixelRatio||1);c.height=innerHeight*(devicePixelRatio||1);if(gl)gl.viewport(0,0,c.width,c.height)}addEventListener('resize',resize);resize();
function sh(t,s){let q=gl.createShader(t);gl.shaderSource(q,s);gl.compileShader(q);if(!gl.getShaderParameter(q,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(q));return q}
function init(){gl=c.getContext('webgl',{antialias:true,alpha:false});if(!gl)throw Error('WebGL unavailable');const vs=`attribute vec3 p;attribute vec3 n;uniform mat4 m;varying float L;varying float H;void main(){gl_Position=m*vec4(p,1.);L=.35+.65*max(dot(normalize(n),normalize(vec3(-.4,.9,.25))),0.);H=p.y;}`,fs=`precision mediump float;varying float L;varying float H;void main(){float t=clamp(H*.0015+.45,0.,1.);vec3 a=vec3(.10,.28,.12),b=vec3(.33,.55,.24),d=vec3(.72,.76,.50);vec3 col=mix(a,b,min(1.,t*2.));col=mix(col,d,max(0.,(t-.5)*2.));gl_FragColor=vec4(col*L,1.);}`;prog=gl.createProgram();gl.attachShader(prog,sh(gl.VERTEX_SHADER,vs));gl.attachShader(prog,sh(gl.FRAGMENT_SHADER,fs));gl.linkProgram(prog);if(!gl.getProgramParameter(prog,gl.LINK_STATUS))throw Error('shader link failed');prog.p=gl.getAttribLocation(prog,'p');prog.n=gl.getAttribLocation(prog,'n');prog.m=gl.getUniformLocation(prog,'m');gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE)}
function pm(f,a,n,z){let q=1/Math.tan(f/2),nf=1/(n-z);return new Float32Array([q/a,0,0,0,0,q,0,0,0,0,(z+n)*nf,-1,0,0,2*z*n*nf,0])}
function la(e,t){let z=[e[0]-t[0],e[1]-t[1],e[2]-t[2]],l=Math.hypot(...z);z=z.map(v=>v/l);let x=[z[1]*0-z[2]*1,z[2]*0-z[0]*0,z[0]*1-z[1]*0],xl=Math.hypot(...x);x=x.map(v=>v/xl);let y=[z[1]*x[2]-z[2]*x[1],z[2]*x[0]-z[0]*x[2],z[0]*x[1]-z[1]*x[0]];return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-(x[0]*e[0]+x[1]*e[1]+x[2]*e[2]),-(y[0]*e[0]+y[1]*e[1]+y[2]*e[2]),-(z[0]*e[0]+z[1]*e[1]+z[2]*e[2]),1])}
function mul(a,b){let o=new Float32Array(16);for(let r=0;r<4;r++)for(let col=0;col<4;col++)o[r*4+col]=a[r*4]*b[col]+a[r*4+1]*b[4+col]+a[r*4+2]*b[8+col]+a[r*4+3]*b[12+col];return o}
async function loadOBJ(){if(loading||loaded)return;loading=true;try{init();const r=await fetch('fnscan.obj');if(!r.ok)throw Error('fnscan.obj not found');const text=await r.text();document.getElementById('objDetail').textContent='Parsing 3D geometry…';const V=[],P=[],N=[],mn=[Infinity,Infinity,Infinity],mx=[-Infinity,-Infinity,-Infinity],lines=text.split(/\r?\n/);for(const line of lines){if(line.startsWith('v ')){const a=line.trim().split(/\s+/),x=+a[1],y=+a[2],z=+a[3];V.push(x,y,z);mn[0]=Math.min(mn[0],x);mn[1]=Math.min(mn[1],y);mn[2]=Math.min(mn[2],z);mx[0]=Math.max(mx[0],x);mx[1]=Math.max(mx[1],y);mx[2]=Math.max(mx[2],z)}}const center=[(mn[0]+mx[0])/2,(mn[1]+mx[1])/2,(mn[2]+mx[2])/2],scale=900/Math.max(mx[0]-mn[0],mx[2]-mn[2],mx[1]-mn[1]);for(let i=0;i<lines.length;i++){const line=lines[i];if(!line.startsWith('f '))continue;const ids=line.trim().split(/\s+/).slice(1).map(s=>parseInt(s.split('/')[0],10));for(let k=1;k<ids.length-1;k++){const ii=[ids[0],ids[k],ids[k+1]].map(n=>n<0?V.length/3+n:n-1),p=[];for(const id of ii)p.push([V[id*3],V[id*3+1],V[id*3+2]]);const ux=p[1][0]-p[0][0],uy=p[1][1]-p[0][1],uz=p[1][2]-p[0][2],vx=p[2][0]-p[0][0],vy=p[2][1]-p[0][1],vz=p[2][2]-p[0][2],nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx,L=Math.hypot(nx,ny,nz)||1;for(const q of p){P.push((q[0]-center[0])*scale,(q[1]-center[1])*scale,(q[2]-center[2])*scale);N.push(nx/L,ny/L,nz/L)}}if(i%5000===0){const pct=Math.min(99,Math.round(i/lines.length*100));document.querySelector('#objBar i').style.width=pct+'%';document.getElementById('objDetail').textContent='Parsing geometry… '+pct+'%';await new Promise(requestAnimationFrame)}}pb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,pb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(P),gl.STATIC_DRAW);nb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,nb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(N),gl.STATIC_DRAW);count=P.length/3;loaded=true;load.style.display='none';if(oldCanvas)oldCanvas.style.display='none'}catch(e){document.getElementById('objStatus').textContent='3D MAP LOAD FAILED';document.getElementById('objDetail').textContent=e.message;console.error(e)}}
function active(){return getComputedStyle(game).display!=='none'&&!game.classList.contains('hidden')}
const mo=new MutationObserver(()=>{if(active()){if(oldCanvas)oldCanvas.style.display='none';if(!loaded)loadOBJ()}else{if(oldCanvas)oldCanvas.style.display='block';load.style.display='none'}});mo.observe(game,{attributes:true,attributeFilter:['class','style']});
function update(dt){if(!active())return;let sp=(keys.ShiftLeft||keys.ShiftRight)?130:75,s=Math.sin(pos.yaw),c0=Math.cos(pos.yaw),f=0,r=0;if(keys.KeyW)f++;if(keys.KeyS)f--;if(keys.KeyA)r--;if(keys.KeyD)r++;let L=Math.hypot(f,r)||1;pos.x+=(r*c0+f*s)/L*sp*dt;pos.z+=(f*c0-r*s)/L*sp*dt;if(keys.Space)pos.y+=70*dt;if(keys.ControlLeft||keys.ControlRight)pos.y-=70*dt;pos.y=Math.max(8,Math.min(650,pos.y))}
function draw(){if(!active()||!gl||!loaded)return;gl.clearColor(.38,.72,.88,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const s=Math.sin(pos.yaw),c0=Math.cos(pos.yaw),cp=Math.cos(pos.pitch),sp=Math.sin(pos.pitch),front=[s*cp,sp,c0*cp],eye=[pos.x-front[0]*dist,pos.y-front[1]*dist,pos.z-front[2]*dist],m=mul(pm(1.02,c.width/c.height,.5,4500),la(eye,[pos.x,pos.y-15,pos.z]));gl.useProgram(prog);gl.uniformMatrix4fv(prog.m,false,m);gl.bindBuffer(gl.ARRAY_BUFFER,pb);gl.enableVertexAttribArray(prog.p);gl.vertexAttribPointer(prog.p,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,nb);gl.enableVertexAttribArray(prog.n);gl.vertexAttribPointer(prog.n,3,gl.FLOAT,false,0,0);gl.drawArrays(gl.TRIANGLES,0,count)}
let last=performance.now();(function loop(t){let dt=Math.min(.05,(t-last)/1000);last=t;update(dt);draw();requestAnimationFrame(loop)})(last);})();